<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Employees [
        <!ELEMENT Employees (Employee)*>
        <!ELEMENT Employee (age?, name?, gender+, role*)>
        <!ATTLIST Employee
                id CDATA #REQUIRED
                >
        <!ELEMENT age (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT gender (#PCDATA)>
        <!ELEMENT role (#PCDATA)>
        ]>
<Employees>
    <Employee id="1">
        <age>29</age>
        <name>Pankaj</name>
        <gender>Male</gender>
        <role>Java Developer</role>
    </Employee>
</Employees>